name: Update dependencies

on:
  workflow_dispatch: []
  # schedule:
  #   - cron: "0 0 * * 1"
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repositoy
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm ci
      - name: Update WordPress
        run: |
          composer require roots/wordpress
          npm run build
      - name: Check for changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.7
        with:
          files: dist/*.scss
      - name: Get new version
        id: version
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: echo "::set-output name=VERSION::$(composer show roots/wordpress -f json | jq '.source.reference')"
      - name: Debug
        run: echo ${{ steps.version.outputs.VERSION }}
#       - name: Create pull request
#         uses: peter-evans/create-pull-request@v4
#         if: steps.changed-files-specific.outputs.any_changed == 'true'
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           add-paths: |
#             composer.*
#             dist
#           commit-message: Update dependencies
#           title: Update dependencies
#           body: |
#             - Dependency updates
#
#             Auto-generated by [create-pull-request][1]
#
#             [1]: https://github.com/peter-evans/create-pull-request
#           branch: update-dependencies
